language: python
python:
  - "2.7"
services:
  - mongodb
  - memcached
before_install:
  - sudo apt-get install beanstalkd
install:
  - pip install -r requirements-dev.txt --use-mirrors
script:
  - sudo mkdir -p /opt/logs/webscrapper/
  - sudo chmod 777 /opt/logs
  - make tests
after_script:
  - coveralls